name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run unit tests
        run: npm test

      - name: Lint code
        run: npm run lint

      - name: Run static analysis
        run: npm run analyze

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/

      - name: Deploy to server
        run: |
          echo "Deploying to production server..."
          # Aquí puedes añadir comandos para copiar archivos al servidor, por ejemplo:
          # scp -r build/* user@server:/path/to/deployment

  verify_deployment:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          # Aquí puedes añadir comandos para verificar el despliegue, por ejemplo:
          # curl -f http://server/path/to/deployment || exit 1
