name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm ci
          # Instalación de dependencias usando npm ci para garantizar la reproducibilidad del entorno

      - name: Build artifact
        run: |
          npm run build
          # Compilación del proyecto usando npm run build

      - name: Run unit tests
        run: |
          npm test
          # Ejecución de pruebas unitarias usando npm test

      - name: Lint code
        run: |
          npm run lint
          # Linting del código usando npm run lint

      - name: Run static analysis
        run: |
          npm run analyze
          # Análisis estático del código usando npm run analyze

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/

      - name: Deploy to production
        run: |
          # Comandos para desplegar en producción, por ejemplo, copiar los archivos a un servidor
          scp -r build/* user@server:/path/to/deployment

  verify_deployment:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Verify deployment
        run: |
          # Comandos para verificar el despliegue, por ejemplo, realizar una solicitud HTTP a la aplicación desplegada y verificar la respuesta
          curl http://deployed-server:port/
