name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: '.'  # Indicamos que queremos que el código se guarde en la raíz del proyecto

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-pip -y
          pip3 install -r requirements.txt

      - name: Build artifact
        run: |
          python3 build.py
          # Reemplaza build.py con el comando real para construir tu proyecto

      - name: Run unit tests
        run: |
          pytest
          # Suponiendo que estás utilizando pytest para tus pruebas unitarias

      - name: Lint code
        run: |
          pylint *.py
          # Suponiendo que estás utilizando pylint para linting

      - name: Static analysis
        run: |
          bandit -r .
          # Suponiendo que estás utilizando Bandit para el análisis estático de seguridad

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./path/to/artifact  # Ahora la ruta será relativa a la raíz del proyecto

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: '.'  # Indicamos que queremos que el código se guarde en la raíz del proyecto

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./path/to/artifact  # Ahora la ruta será relativa a la raíz del proyecto

      - name: Deploy to server
        run: |
          echo "Deploying to server..."
          # Aquí pondrías tus comandos de despliegue, como scp, rsync, etc.

  verify_deployment:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          # Aquí pondrías comandos para verificar que el despliegue fue exitoso
