name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build artifact
        run: |
          # Aquí deberías poner tus comandos reales de construcción
          echo "Building project..."
          # Ejemplo de comando de construcción: npm run build

      - name: Run unit tests
        run: |
          # Ejemplo de comando para ejecutar pruebas unitarias
          echo "Running unit tests..."
          # Ejemplo de comando para pruebas unitarias: npm test

      - name: Lint code
        run: |
          # Ejemplo de comando para ejecutar el linter
          echo "Linting code..."
          # Ejemplo de comando para linting: eslint .

      - name: Run static analysis
        run: |
          # Ejemplo de comando para análisis estático
          echo "Running static analysis..."
          # Ejemplo de comando para análisis estático: sonar-scanner

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/

      - name: Deploy to server
        run: |
          # Aquí deberías poner los comandos reales de despliegue
          echo "Deploying to server..."
          # Ejemplo de comando de despliegue: scp build/* user@server:/path/to/deployment

  verify_deployment:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Verify deployment
        run: |
          # Aquí deberías poner los comandos reales de verificación de despliegue
          echo "Verifying deployment..."
          # Ejemplo de comandos de verificación: curl http://deployed-server:port/

